### ISSUE TITLE
Finvizor no longer parsing the ticker information correctly

### ISSUE THREAD

**Issue by straimtheone** [samgozman/finvizor#195]
Starting today, the finvizor is query the ticker correctly, however, it no longer maps some properties in the response, the most obvious one would be the symbol, the attached file shows today's answer from AMD query.
[example.txt](https://github.com/samgozman/finvizor/files/12895563/example.txt)

**Comment by samgozman** [comment]
Thanks for sharing! I will fix it tomorrow, most likely finviz just updated their site schema

**Comment by samgozman** [comment]
Fixed in 1.2.0 version
