### ISSUE TITLE
Quote proccessing failed with "TypeError: Cannot read properties of undefined (reading 'split')"

### ISSUE THREAD

**Issue by straimtheone** [samgozman/finvizor#212]
Starting last monday, Finvizor is unable to process the quote information correctly and it is failing with the following error:
`ERROR	Error: TypeError: Cannot read properties of undefined (reading 'split')
    at Object.getStock (/var/task/node_modules/finvizor/lib/quote.js:82:15)`

**Comment by samgozman** [comment]
Are you sure you are using the latest version 1.2.1? On what stock this error I can reproduce?
Because I see that my main project that uses this library working without errors: https://short-fork.extr.app/en/MSFT
And tests for this lib are all green..

**Comment by straimtheone** [comment]
Greetings @samgozman, it seems that it changed for ETF tickers, "MSFT" does works but "QQQ" does not. at least in my code. It took me some time to figure out as I have both mixed in my configuration so at first I thought it was something related to throughput but indeed only happens with ETF tickers.

**Comment by samgozman** [comment]
@straimtheone thank you for noticing! Fixed this error in 1.2.2 version: https://www.npmjs.com/package/finvizor/v/1.2.2

**Comment by straimtheone** [comment]
Working as expected, thank you!
